### PR TITLE
Change event to access old and new path on events

### PR DESCRIPTION
**Pull request by CiolFr**
I've made this little change to allow acces to file path old and new

### CODE REVIEW

**Comment by radovskyb** [comment]
Hey @CiolFr,

Good idea. Can you please write a couple of tests for each event type before I look at merging this in, thanks!

**Comment by CiolFr** [comment]
Hello @radovskyb 
J've just pushed some test as you asked

**Comment by ghostsquad** [comment]
@radovskyb any chance this can be merged? this PR has been hanging out for some time now.

**Comment by freestream** [comment]
I would also want to see this one to get merged, I need this feature

**Comment by radovskyb** [comment]
Hi @CiolFr, 

Sorry for the very delayed response here, just merged this one though, thanks!

I changed the remove event to keep the path in the event instead of leaving it blank, but otherwise all good :)

**Comment by freestream** [comment]
Nice! @radovskyb please aslo bump up the release version

**Comment by CiolFr** [comment]
Thanks for your work :)

**Pull request merged**
